backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"      # Filer lagres her i repoet
public_folder: "/images/uploads"    # Slik refereres de på nettsiden
publish_mode: editorial_workflow
locale: "no"

collections:
  # =========================
  # Felles nettsted-data (site.json)
  # =========================
  - name: "site"
    label: "Nettsted – Felles"
    files:
      - name: "site"
        label: "Fellesinnhold"
        file: "data/site.json"
        fields:
          - { name: orgnr,  label: "Organisasjonsnummer", widget: "string" }
          - { name: footer, label: "Footer-tekst",        widget: "string", default: "Attolloogroup. Alle rettigheter forbeholdt." }

  # =========================
  # Forside (home.json)
  # =========================
  - name: "home"
    label: "Forside"
    files:
      - name: "home"
        label: "Forside"
        file: "data/home.json"
        fields:
          - { name: title,      label: "Tittel (hero)",  widget: "string" }
          - { name: subtitle,   label: "Ingress (hero)", widget: "text", required: false }
          - { name: hero_image, label: "Hero-bilde",     widget: "image", choose_url: true, allow_multiple: false, required: false }
          - label: "Forside-seksjoner"
            name: "sections"
            widget: "list"
            collapsed: true
            fields:
              - { name: heading, label: "Overskrift", widget: "string" }
              - { name: body,    label: "Tekst",      widget: "text" }
              - { name: image,   label: "Bilde",      widget: "image", choose_url: true, required: false }

  # =========================
  # Om oss (about.json)
  # =========================
  - name: "about"
    label: "Om oss"
    files:
      - name: "about"
        label: "Om oss"
        file: "data/about.json"
        fields:
          - { name: title,      label: "Tittel (hero)",  widget: "string" }
          - { name: subtitle,   label: "Ingress (hero)", widget: "text", required: false }
          - { name: hero_image, label: "Hero-bilde",     widget: "image", choose_url: true, allow_multiple: false, required: false }
          - label: "Om oss-seksjoner"
            name: "sections"
            widget: "list"
            collapsed: true
            fields:
              - { name: heading, label: "Overskrift", widget: "string" }
              - { name: body,    label: "Tekst",      widget: "text" }
              - { name: image,   label: "Bilde",      widget: "image", choose_url: true, required: false }

  # =========================
  # Tjenester (services.json)
  # =========================
  - name: "services"
    label: "Tjenester"
    files:
      - name: "servicespage"
        label: "Tjenestesiden"
        file: "data/services.json"
        fields:
          - { name: title,      label: "Tittel (hero)",  widget: "string" }
          - { name: subtitle,   label: "Ingress (hero)", widget: "text", required: false }
          - { name: hero_image, label: "Hero-bilde",     widget: "image", choose_url: true, allow_multiple: false, required: false }
          - label: "Tjenester"
            name: "sections"
            widget: "list"
            collapsed: false
            fields:
              - { name: heading,   label: "Overskrift",    widget: "string" }
              - { name: body,      label: "Brødtekst",     widget: "text" }
              - { name: image,     label: "Bilde",         widget: "image", choose_url: true, required: false }
              - { name: imageTall, label: "Større bilde",  widget: "boolean", required: false, default: false }

  # =========================
  # Blogg (Markdown-innlegg i /blog/posts)
  # =========================
  - name: "posts"
    label: "Blogginnlegg"
    label_singular: "Innlegg"
    folder: "blog/posts"                    # .md-filer lagres her
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/post.html?p={{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Tittel",               name: "title",   widget: "string" }
      - { label: "Dato",                 name: "date",    widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Ingress (kort)",       name: "excerpt", widget: "text", required: false }
      - { label: "Forsidebilde (cover)", name: "cover",   widget: "image", required: false }
      - { label: "Innhold",              name: "body",    widget: "markdown" }
